config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :incidences
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/incidence.rb
class Incidence < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/control_controller.rb
class ControlController < ApplicationController

end

app/controllers/incidences_controller.rb
class IncidencesController < ApplicationController

def new	
end

def create
#render plain: params[:incidence].inspect 
@incidence = Incidence.new (incidence_params)
@incidence.save
redirect_to @incidence
end

def show
  @incidence = Incidence.find(params[:id])
end


private
def incidence_params
	params.require(:incidence).permit(:num_radicado, :decripcion, :fecha_registro, :fecha_incidente, :adjunto,:estado)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/incidences_helper.rb
module IncidencesHelper
end

app/views/incidences/new.html.erb
<p>REGISTRAR UNA INCIDENCIA</p>

<%= form_for :incidence, url: incidences_path do |f| %>
<%= f.label :Número_radicado %> <br>
<%= f.text_field :num_radicado %> <br><br>
<%= f.label :Descripcion_incidencia %> <br>
<%= f.text_field :descripcion %> <br><br>
<%= f.label :Fecha_registro %> <br>
<%= f.date_select :fecha_registro %> <br><br>
<%= f.label :Fecha_incidencia %> <br>
<%= f.date_select :fecha_incidencia %> <br><br>
<%= f.label :Adjunto %> <br>
<%= f.text_field :adjunto %> <br><br>
<%= f.label :Estado_incidencia %> <br>
<%= f.text_field :estado %> <br><br><br>
<%= f.submit %>
<%end%>

app/views/incidences/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @incidence.num_radicado %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @incidence.descripcion %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appwebjaboque</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>